spring:
  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:33066/mongoo_life?serverTimezone=UTC&characterEncoding=UTF-8}
    username: ${DB_USERNAME:mongoo}
    password: ${DB_PASSWORD:mongoo_password}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        jdbc:
          time_zone: UTC
    show-sql: true
    open-in-view: false

jwt:
  secret: ${JWT_SECRET}
  access-token-validity-in-seconds: 1800
  refresh-token-validity-in-seconds: 604800
